spring.application.name=library

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://dpg-d6rrmm14tr6s73a9uspg-a.frankfurt-postgres.render.com/online_library_db_ajpp
spring.datasource.username=library_user
spring.datasource.password=fEM4x0TNizFTefUYjZRubApbto9dI55a

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=e9f784b04799b6
spring.mail.password=39bbfb5b787fb1
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

frontend.url="https://library-front-3qvv.onrender.com/"

